#!/usr/env python
presets={}
presets['airplane']={'thid':4112,'shortname':'orig3dmm_airplane','name':"3dmm: Airplane",'actor':False}
presets['balloon']={'thid':4113,'shortname':'orig3dmm_balloon','name':"3dmm: Balloon",'actor':False}
presets['parachute']={'thid':4114,'shortname':'orig3dmm_parachute','name':"3dmm: Parachute",'actor':False}
presets['rocket']={'thid':4115,'shortname':'orig3dmm_rocket','name':"3dmm: Rocket",'actor':False}
presets['spaceship']={'thid':4116,'shortname':'orig3dmm_spaceship','name':"3dmm: Spaceship",'actor':False}
presets['ambulance']={'thid':4117,'shortname':'orig3dmm_ambulance','name':"3dmm: Ambulance",'actor':False}
presets['car']={'thid':4118,'shortname':'orig3dmm_car','name':"3dmm: Car",'actor':False}
presets['policecar']={'thid':4119,'shortname':'orig3dmm_policecar','name':"3dmm: Police car",'actor':False}
presets['taxi']={'thid':4120,'shortname':'orig3dmm_taxi','name':"3dmm: Taxi",'actor':False}
presets['coffin']={'thid':4121,'shortname':'orig3dmm_coffin','name':"3dmm: Coffin",'actor':False}
presets['safe']={'thid':4122,'shortname':'orig3dmm_safe','name':"3dmm: Safe",'actor':False}
presets['tent']={'thid':4124,'shortname':'orig3dmm_tent','name':"3dmm: Tent",'actor':False}
presets['totempole1']={'thid':4125,'shortname':'orig3dmm_totempole1','name':"3dmm: Totem pole 1",'actor':False}
presets['totempole2']={'thid':4126,'shortname':'orig3dmm_totempole2','name':"3dmm: Totem pole 2",'actor':False}
presets['treasurechest']={'thid':4127,'shortname':'orig3dmm_treasurechest','name':"3dmm: Treasure chest",'actor':False}
presets['earth']={'thid':4128,'shortname':'orig3dmm_earth','name':"3dmm: Earth",'actor':False}
presets['explosio']={'thid':4129,'shortname':'orig3dmm_explosio','name':"3dmm: Explosio",'actor':False}
presets['cube']={'thid':4130,'shortname':'orig3dmm_cube','name':"3dmm: Cube",'actor':False}
presets['sphere']={'thid':4131,'shortname':'orig3dmm_sphere','name':"3dmm: Sphere",'actor':False}
presets['cylinder']={'thid':4132,'shortname':'orig3dmm_cylinder','name':"3dmm: Cylinder",'actor':False}
presets['torus']={'thid':4133,'shortname':'orig3dmm_torus','name':"3dmm: Torus",'actor':False}
presets['alexander']={'thid':8208,'shortname':'orig3dmm_alexander','name':"3dmm: Alexander",'actor':True}
presets['augustin']={'thid':8209,'shortname':'orig3dmm_augustin','name':"3dmm: Augustin",'actor':True}
presets['bella']={'thid':8210,'shortname':'orig3dmm_bella','name':"3dmm: Bella",'actor':True}
presets['benedict']={'thid':8211,'shortname':'orig3dmm_benedict','name':"3dmm: Benedict",'actor':True}
presets['billy']={'thid':8212,'shortname':'orig3dmm_billy','name':"3dmm: Billy",'actor':True}
presets['binobegood']={'thid':8213,'shortname':'orig3dmm_binobegood','name':"3dmm: Bino BeGood",'actor':True}
presets['bo']={'thid':8214,'shortname':'orig3dmm_bo','name':"3dmm: Bo",'actor':True}
presets['bongo']={'thid':8215,'shortname':'orig3dmm_bongo','name':"3dmm: Bongo",'actor':True}
presets['charlie']={'thid':8216,'shortname':'orig3dmm_charlie','name':"3dmm: Charlie",'actor':True}
presets['christina']={'thid':8217,'shortname':'orig3dmm_christina','name':"3dmm: Christina",'actor':True}
presets['claudia']={'thid':8218,'shortname':'orig3dmm_claudia','name':"3dmm: Claudia",'actor':True}
presets['crash']={'thid':8219,'shortname':'orig3dmm_crash','name':"3dmm: Crash",'actor':True}
presets['eliza']={'thid':8220,'shortname':'orig3dmm_eliza','name':"3dmm: Eliza",'actor':True}
presets['frank']={'thid':8221,'shortname':'orig3dmm_frank','name':"3dmm: Frank",'actor':True}
presets['gabriel']={'thid':8222,'shortname':'orig3dmm_gabriel','name':"3dmm: Gabriel",'actor':True}
presets['gregory']={'thid':8223,'shortname':'orig3dmm_gregory','name':"3dmm: Gregory",'actor':True}
presets['gustave']={'thid':8224,'shortname':'orig3dmm_gustave','name':"3dmm: Gustave",'actor':True}
presets['henry']={'thid':8225,'shortname':'orig3dmm_henry','name':"3dmm: Henry",'actor':True}
presets['hiro']={'thid':8226,'shortname':'orig3dmm_hiro','name':"3dmm: Hiro",'actor':True}
presets['jeremy']={'thid':8227,'shortname':'orig3dmm_jeremy','name':"3dmm: Jeremy",'actor':True}
presets['jerzy']={'thid':8228,'shortname':'orig3dmm_jerzy','name':"3dmm: Jerzy",'actor':True}
presets['josephine']={'thid':8229,'shortname':'orig3dmm_josephine','name':"3dmm: Josephine",'actor':True}
presets['kim']={'thid':8230,'shortname':'orig3dmm_kim','name':"3dmm: Kim",'actor':True}
presets['maribella']={'thid':8231,'shortname':'orig3dmm_maribella','name':"3dmm: Maribella",'actor':True}
presets['martha']={'thid':8232,'shortname':'orig3dmm_martha','name':"3dmm: Martha",'actor':True}
presets['michael']={'thid':8233,'shortname':'orig3dmm_michael','name':"3dmm: Michael",'actor':True}
presets['mimi']={'thid':8234,'shortname':'orig3dmm_mimi','name':"3dmm: Mimi",'actor':True}
presets['nakita']={'thid':8235,'shortname':'orig3dmm_nakita','name':"3dmm: Nakita",'actor':True}
presets['patrick']={'thid':8236,'shortname':'orig3dmm_patrick','name':"3dmm: Patrick",'actor':True}
presets['ramu']={'thid':8237,'shortname':'orig3dmm_ramu','name':"3dmm: Ramu",'actor':True}
presets['randolph']={'thid':8238,'shortname':'orig3dmm_randolph','name':"3dmm: Randolph",'actor':True}
presets['roxanne']={'thid':8239,'shortname':'orig3dmm_roxanne','name':"3dmm: Roxanne",'actor':True}
presets['skelly']={'thid':8240,'shortname':'orig3dmm_skelly','name':"3dmm: S'kelly",'actor':True}
presets['salvador']={'thid':8241,'shortname':'orig3dmm_salvador','name':"3dmm: Salvador",'actor':True}
presets['sebastian']={'thid':8242,'shortname':'orig3dmm_sebastian','name':"3dmm: Sebastian",'actor':True}
presets['slam']={'thid':8243,'shortname':'orig3dmm_slam','name':"3dmm: Slam",'actor':True}
presets['timothy']={'thid':8244,'shortname':'orig3dmm_timothy','name':"3dmm: Timothy",'actor':True}
presets['valentine']={'thid':8245,'shortname':'orig3dmm_valentine','name':"3dmm: Valentine",'actor':True}
presets['venie']={'thid':8246,'shortname':'orig3dmm_venie','name':"3dmm: Venie",'actor':True}
presets['wanda']={'thid':8247,'shortname':'orig3dmm_wanda','name':"3dmm: Wanda",'actor':True}
presets['willy']={'thid':8248,'shortname':'orig3dmm_willy','name':"3dmm: Willy",'actor':True}
presets['zack']={'thid':8249,'shortname':'orig3dmm_zack','name':"3dmm: Zack",'actor':True}
presets['cathyscratch']={'thid':8250,'shortname':'orig3dmm_cathyscratch','name':"3dmm: Cathy Scratch",'actor':True}
presets['fabricetherat']={'thid':8251,'shortname':'orig3dmm_fabricetherat','name':"3dmm: Fabrice the Rat",'actor':True}
presets['sashathedog']={'thid':8252,'shortname':'orig3dmm_sashathedog','name':"3dmm: Sasha the Dog",'actor':True}

